<?php
require_once('TCPDF/tcpdf.php');

// Database connection
$host = 'localhost';
$dbname = 'lupao_portal';
$username = 'root';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname", $username);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    die("Database connection failed: " . $e->getMessage());
}

// Fetch data from the database with status = 1
$query = "
    SELECT
        u.lastname, u.firstname, u.birthday, u.gender, u.contact_no, u.email, u.baranggay,
        sp.program_title, sp.beneficiaries, sp.description, sp.grantor,
        ss.date_approved
    FROM scholarships_scholars ss
    INNER JOIN user_table u ON ss.student_id = u.id
    INNER JOIN scholarship_programs sp ON ss.program_id = sp.id
    WHERE ss.status = 1
";
$stmt = $pdo->prepare($query);
$stmt->execute();
$data = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Create new PDF document
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Organization');
$pdf->SetTitle('Scholarship Report');
$pdf->SetSubject('Scholarship Program Details');

// Set default header data
$pdf->SetHeaderData('', 0, 'Scholarship Report', "Generated on: " . date('Y-m-d'));

// Set header and footer fonts
$pdf->setHeaderFont(['helvetica', '', 12]);
$pdf->setFooterFont(['helvetica', '', 10]);

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(15, 27, 15);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(10);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 25);

// Cover Page
$pdf->AddPage();
$pdf->SetFont('helvetica', 'B', 20);
$pdf->Cell(0, 10, 'Scholarship Program Report', 0, 1, 'C');
$pdf->Ln(10);
$pdf->SetFont('helvetica', '', 14);
$pdf->Cell(0, 10, 'Generated by Your Organization', 0, 1, 'C');
$pdf->Ln(20);
$pdf->SetFont('helvetica', '', 12);
$pdf->Cell(0, 10, 'Date: ' . date('F d, Y'), 0, 1, 'C');
$pdf->AddPage();

// Loop through each record and format the output in table layout
foreach ($data as $row) {
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor(200, 230, 255);
    $pdf->Cell(0, 10, 'Scholar Details', 0, 1, 'L', true);

    $pdf->SetFont('helvetica', '', 10);
    $pdf->Ln(2);

    $pdf->SetFillColor(240, 248, 255);
    $pdf->Cell(50, 8, 'Name:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['firstname'] . " " . $row['lastname'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Birthday:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['birthday'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Gender:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['gender'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Contact No:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['contact_no'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Email:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['email'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Barangay:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['baranggay'], 1, 1, 'L');

    $pdf->Cell(0, 10, 'Scholarship Program Details', 0, 1, 'L', true);
    $pdf->SetFont('helvetica', '', 10);

    $pdf->Cell(50, 8, 'Program Title:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['program_title'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Beneficiaries:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['beneficiaries'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Description:', 1, 0, 'L', true);
    $pdf->MultiCell(130, 8, $row['description'], 1, 'L');

    $pdf->Cell(50, 8, 'Grantor:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['grantor'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Date Approved:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['date_approved'], 1, 1, 'L');
    $pdf->Ln(10);
}

// Footer with page number
$pdf->setPrintFooter(true);
$pdf->SetFooterData([0, 0, 0], [0, 0, 0]);
$pdf->SetFooterMargin(10);
$pdf->setFooterFont(['helvetica', '', 8]);

// Output the PDF
$pdf->Output('scholarship_report.pdf', 'I');
?>
