<?php
require_once('TCPDF/tcpdf.php');

// Database connection
$host = 'localhost';
$dbname = 'lupao_portal';
$username = 'root';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$dbname", $username);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    die("Database connection failed: " . $e->getMessage());
}

// Fetch data from the database, sorted by role priority
$query = "
    SELECT
        ut.role,
        u.firstname,
        u.lastname,
        u.email,
        u.baranggay,
        u.contact_no,
        u.birthday,
        u.gender,
        u.created_at,
        CASE
            WHEN u.status = 1 THEN 'Approved'
            WHEN u.status = 3 THEN 'Disabled'
            ELSE 'Pending'
        END AS status
    FROM user_table u
    INNER JOIN user_type ut ON u.user_type = ut.id
    ORDER BY
        CASE ut.role
            WHEN 'Admin' THEN 1
            WHEN 'Employer' THEN 2
            WHEN 'Applicant' THEN 3
            ELSE 4
        END,
        u.lastname ASC, u.firstname ASC
";
$stmt = $pdo->prepare($query);
$stmt->execute();
$data = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Create new PDF document
$pdf = new TCPDF();
$pdf->SetCreator(PDF_CREATOR);
$pdf->SetAuthor('Your Organization');
$pdf->SetTitle('User Report');
$pdf->SetSubject('User Details by Role');

// Set default header data
$pdf->SetHeaderData('', 0, 'User Report', "Generated on: " . date('Y-m-d'));

// Set header and footer fonts
$pdf->setHeaderFont(['helvetica', '', 12]);
$pdf->setFooterFont(['helvetica', '', 10]);

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(15, 27, 15);
$pdf->SetHeaderMargin(5);
$pdf->SetFooterMargin(10);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, 25);

// Add Cover Page
$pdf->AddPage();
$pdf->SetFont('helvetica', '', 12);
$pdf->Cell(0, 10, 'Lupao, Nueva Ecija, 3122', 0, 1, 'C');
$pdf->Ln(10);
$pdf->SetFont('helvetica', 'B', 20);
$pdf->Cell(0, 10, 'User Report by Role', 0, 1, 'C');
$pdf->Ln(10);
$pdf->SetFont('helvetica', '', 14);
$pdf->Cell(0, 10, 'Generated by Your Organization', 0, 1, 'C');
$pdf->Ln(20);
$pdf->SetFont('helvetica', '', 12);
$pdf->Cell(0, 10, 'Date: ' . date('F d, Y'), 0, 1, 'C');
$pdf->AddPage();

// Loop through each record and format the output in table layout
foreach ($data as $row) {
    $pdf->SetFont('helvetica', 'B', 12);
    $pdf->SetFillColor(200, 230, 255);
    $pdf->Cell(0, 10, 'User Details', 0, 1, 'L', true);

    $pdf->SetFont('helvetica', '', 10);
    $pdf->Ln(2);

    $pdf->SetFillColor(240, 248, 255);
    $pdf->Cell(50, 8, 'Role:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['role'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Name:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['firstname'] . " " . $row['lastname'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Email:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['email'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Barangay:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['baranggay'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Contact No:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['contact_no'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Birthday:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['birthday'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Gender:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['gender'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Created At:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['created_at'], 1, 1, 'L');

    $pdf->Cell(50, 8, 'Status:', 1, 0, 'L', true);
    $pdf->Cell(130, 8, $row['status'], 1, 1, 'L');
    $pdf->Ln(10);
}

// Footer with page number
$pdf->setPrintFooter(true);
$pdf->SetFooterData([0, 0, 0], [0, 0, 0]);
$pdf->SetFooterMargin(10);
$pdf->setFooterFont(['helvetica', '', 8]);

// Output the PDF
$pdf->Output('user_report.pdf', 'I');
?>
